version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    volumes:
      - ./poker.db:/app/poker.db
      - ./rooms_state.pickle:/app/rooms_state.pickle
      - ./logs:/app/logs
    ports:
      - "8000:8000"  # 可选，用于直接测试API
    environment:
      - SECRET_KEY=c32poker_secret_key  # 生产环境应修改为更安全的密钥

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - REACT_APP_API_URL=http://${SERVER_HOST:-localhost}  # 运行时传入SERVER_HOST环境变量
    restart: always
    ports:
      - "8888:80"  # 将宿主机的8888端口映射到容器的80端口
    depends_on:
      - backend

# 可选的持久化卷配置
volumes:
  db-data:
  game-state: 